package com.owilka.hotel.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Document(collection = "rooms")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Room {
    
    @Id
    private String id;
    
    private String roomTypeName;
    private Double pricePerNight;
    private Integer totalRooms;
    private Integer occupiedRooms;
    private String roomSize;
    private String bedType;
    private Integer maxOccupancy;
    private String viewType;
    private Integer floorNumber;
    private String description;
    private List<String> amenities;
    private String imageUrl;
    private String status; // active, inactive, maintenance
    
    // Getters and Setters are automatically generated by Lombok @Data annotation
    
    // You can add custom methods if needed
    public int getAvailableRooms() {
        return totalRooms - (occupiedRooms != null ? occupiedRooms : 0);
    }
    
    public boolean isAvailable() {
        return getAvailableRooms() > 0 && "active".equalsIgnoreCase(status);
    }
}
